# Generated by Django 5.0.1 on 2024-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
