# Generated by Django 5.0.1 on 2024-02-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_save_owner_alter_save_post_comment_like'),
        ('posts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='save',
            new_name='is_saved',
        )
    ]
